sudo: required
language: python

services:
  - docker

python:
    - 3.5

before_install:
    - sudo apt-get update

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=

install:
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov

script:
    - make docker_build
    - make docker_cov

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    - codecov
