language: python

python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update
    - sudo apt-get install unixODBC
    - sudo apt-get install unixODBC-dev
    - sudo apt-get install sqlite3
    - sudo apt-get install libsqliteodbc
    - sudo apt-get install odbc-postgresql

before_script:
  - psql -c "create database aioodbc;" -U postgres
  - psql -c "create user aioodbc with password 'passwd';" -U postgres
  - psql -c "grant all privileges on database aioodbc to aioodbc;" -U postgres

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

install:
    - pip install -Ur requirements-dev.txt
    - pip install -e .
    - pip install coveralls

script:
    - make cov

after_success:
    - coveralls
