sudo: required
language: python

services:
  - docker

python:
    - 3.5

addons:
  postgresql: "9.2"
  mysql: "5.5"

before_install:
    - sudo apt-get update
    - sudo apt-get install unixODBC
    - sudo apt-get install unixODBC-dev
    - sudo apt-get install odbc-postgresql
    - sudo apt-get install libsqliteodbc
    - sudo apt-get install libmyodbc
    - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
    - sudo cat /etc/odbcinst.ini
    - sudo cat /etc/odbc.ini

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

install:
    - pip install -Ur requirements-dev.txt
    - pip install -e .
    - pip install coveralls

script:
    - make cov

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

after_success:
    - coveralls
