language: python

python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq unixODBC
    - sudo apt-get install -qq unixODBC-dev
    - sudo apt-get install -qq sqlite3
    - sudo apt-get install -qq libsqliteodbc
    - sudo apt-get install -qq odbc-postgresql
    - sudo apt-get install -qq libmyodbc
    - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
    - sudo cat /etc/odbcinst.ini
    - sudo cat /etc/odbc.ini


before_script:
  - psql -c "create database aioodbc;" -U postgres
  - psql -c "create user aioodbc with password 'passwd';" -U postgres
  - psql -c "grant all privileges on database aioodbc to aioodbc;" -U postgres
  - "mysql -e 'SELECT VERSION()'"
  - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql; create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
  - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql2; create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

install:
    - pip install -Ur requirements-dev.txt
    - pip install -e .
    - pip install coveralls

script:
    - make cov

after_success:
    - coveralls
