language: python

python:
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update
    - sudo apt-get install unixODBC
    - sudo apt-get install sqlite3 libsqlite3-dev, libsqliteodbc
    - sleep 1

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

install:
    - pip install flake8
    - pip install pytest
    - pip install coverage
    - pip install .
    - pip install coveralls

script:
    - make cov

after_success:
    - coveralls
